export const questions = [
    "What would be the most embarrassing thing to yell out during a wedding?",
    "If animals could text, what would your dog's last message to you be?",
    "What would be the worst thing to find in your food at a fancy restaurant?",
    "If you had to give up one of your senses, which one would you choose and how would you survive?",
    "What's the dumbest thing you've ever done for the sake of looking cool?",
    "If your body had a 'low battery' warning, where would the sound come from and what would it say?",
    "What would be the worst possible name for a pet goldfish?",
    "If you were a villain, what's your signature evil laugh and catchphrase?",
    "What's the most ridiculous reason you've ever given for being late?",
    "If you had to perform a talent show, what embarrassing trick would you do to win?",
    "What's the worst possible thing to accidentally say to a stranger while trying to make small talk?",
    "If you could only communicate by making sound effects, which one would you use to express excitement?",
    "What's the most bizarre thing you've done while sleepwalking or sleep talking?",
    "If you had to wear a costume to every family dinner, what costume would you choose to wear for eternity?",
    "What's the weirdest thing you've ever done to impress someone and failed spectacularly?",
    "If your pet could run for president, what would be its campaign slogan?",
    "What would be the absolute worst superpower to have during a job interview?",
    "If you could erase one embarrassing thing you've done, but it would still live on in your search history, what would you choose?",
    "What's the most awkward thing you've done while trying to escape a conversation you didn't want to have?",
    "If you were turned into a meme, what would the caption be and what would your picture look like?",
    "If you were to start a conspiracy theory, what would it be about, and how would it go horribly wrong?",
    "What's the worst thing you could overhear someone saying about you at a party?",
    "If you could invent a new ice cream flavor, what would it taste like and what would you name it?",
    "If you had to come up with a new Olympic sport, what would it be and what ridiculous rules would it have?",
    "If your clothes could vote, what would they vote for and why?",
    "What would be the worst thing to accidentally include in a wedding speech?",
    "If you were the villain in a superhero movie, what would your ridiculous, over-the-top evil plan be?",
    "What's the worst possible thing to see in your inbox when you check your email in the morning?",
    "If you could write a completely useless law that everyone had to follow, what would it be?",
    "What would be the least intimidating superpower to have in a fight with a superhero?",
    "If you had to rename a major city, what would you change its name to, and why?",
    "What's the most uncomfortable thing you could do at a public event without getting kicked out?",
    "If you were a contestant on a game show, what ridiculous answer would you give to the first question?",
    "What would you do if your best friend secretly entered you into a weird talent competition without telling you?",
    "If you could write a viral song, what would the chorus be and how would it go completely off the rails?",
    "What's the most inappropriate thing to say to someone during their job interview?",
    "If your phone could write a review of you, what would it say?",
    "What's the most ridiculous excuse you could give for not doing your homework, and still somehow get away with it?",
    "If your embarrassing childhood nickname came back to haunt you, how would you explain it?",
    "What would be the most absurd thing to wear on a first date to make a lasting impression?",
    "If you had to make a reality show about your life, what would the title be, and what would be the weirdest part?",
    "If you could have any animal as a sidekick, but it was completely useless, which animal would you choose and what would it do?",
    "What's the most awkward thing you could say during a job interview and still somehow get hired?",
    "If you had to make a totally weird New Year's resolution, what would it be?",
    "What's the worst thing to find when you open a gift at a birthday party?",
    "If you could create a new, completely nonsensical holiday, what would it be and how would people celebrate it?",
    "If you were trapped on a desert island and could only bring one useless item, what would it be?",
    "If your shoes could talk, what embarrassing things would they reveal about your life?",
    "What's the least helpful superpower someone could have in an apocalypse?",
    "What's the most awkward thing you've ever done when trying to get someone's attention?"
];